<?php

namespace App\Models\Transaction\Invoice;

use App\Models\PaymentMethod\Account;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Traits\HasTable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * @property string $id
 * @property int $status
 * @property Collection $details
 * @property Account $account
 */
class Invoice extends Model
{
    use HasFactory, HasTable;

    const INVOICE_STATUS_CREATED = 1;
    const INVOICE_STATUS_WAITING_PAYMENT = 2;
    const INVOICE_STATUS_WAITING_CONFIRMATION = 3;
    const INVOICE_STATUS_CONFIRMED = 4;
    const INVOICE_STATUS_PAID = 5;
    const INVOICE_STATUS_EXPIRED = 6;
    const INVOICE_STATUS_CANCELED = 7;

    protected $fillable = [
        'status'
    ];

    protected $table = "t_invoices";
    public $incrementing = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub


        static::creating(function (self $invoice) {
            $randomString = Str::random(5);
            $randomString = strtoupper($randomString);
            $dateFormat = (Carbon::now())->format("ymd-His");
            $invoice->setAttribute($invoice->getKeyName(), $randomString . "-" . $dateFormat);
        });
    }

    static public function getAvailableStatus(): array
    {
        return [
            self::INVOICE_STATUS_CREATED,
            self::INVOICE_STATUS_WAITING_PAYMENT,
            self::INVOICE_STATUS_WAITING_CONFIRMATION,
            self::INVOICE_STATUS_CONFIRMED,
            self::INVOICE_STATUS_PAID,
            self::INVOICE_STATUS_EXPIRED,
            self::INVOICE_STATUS_CANCELED,
        ];
    }

    public function details(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Detail::class, 'invoice_id', 'id');
    }

    public function account(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Account::class, 'payment_method_account_id', 'id');
    }
}
