<?php

namespace App\Models\Transaction\Invoice;

use App\Models\PaymentMethod\Account;
use App\Models\Pivot\Transaction\InvoiceAttachment;
use App\Models\Transaction\Transaction;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use App\Traits\HasTable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Jalameta\Attachments\Concerns\Attachable;
use Jalameta\Attachments\Contracts\AttachableContract;
use Jalameta\Attachments\Entities\Attachment;

/**
 * @property string $id
 * @property int $status
 * @property Collection $details
 * @property Account $account
 * @property Attachment $attachment
 */
class Invoice extends Model
{
    use HasFactory, HasTable;

    const INVOICE_STATUS_CREATED = 1;
    const INVOICE_STATUS_WAITING_PAYMENT = 2;
    const INVOICE_STATUS_WAITING_CONFIRMATION = 3;
    const INVOICE_STATUS_CONFIRMED = 4;
    const INVOICE_STATUS_PAID = 5;
    const INVOICE_STATUS_EXPIRED = 6;
    const INVOICE_STATUS_CANCELED = 7;

    protected $fillable = [
        'status'
    ];

    protected $table = "t_invoices";
    public $incrementing = false;

    protected $keyType = 'string';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub


        static::creating(function (self $invoice) {
            $randomString = Str::random(5);
            $randomString = strtoupper($randomString);
            $dateFormat = (Carbon::now())->format("ymd-His");
            $invoice->setAttribute($invoice->getKeyName(), $randomString . "-" . $dateFormat);
        });
    }

    static public function getAvailableStatus(): array
    {
        return [
            self::INVOICE_STATUS_CREATED => 'Created',
            self::INVOICE_STATUS_WAITING_PAYMENT => 'Menunggu Pembayaran',
            self::INVOICE_STATUS_WAITING_CONFIRMATION => 'Menunggu Konfirmasi',
            self::INVOICE_STATUS_CONFIRMED => 'Terkonfirmasi',
            self::INVOICE_STATUS_PAID => 'Telah Terbayar',
            self::INVOICE_STATUS_EXPIRED => 'Kadaluwarsa',
            self::INVOICE_STATUS_CANCELED => 'Dibatalkan',
        ];
    }

    public function details(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Detail::class, 'invoice_id', 'id');
    }

    public function account(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Account::class, 'payment_method_account_id', 'id');
    }

    public function transaction(): \Illuminate\Database\Eloquent\Relations\MorphToMany
    {
        return $this->morphedByMany(Transaction::class, 'invoiceable', 't_invoiceables', 'invoice_id', 'invoiceable_id');
    }

    public function getAttachmentAttribute()
    {
        return $this->attachments()->latest()->first();
    }

    public function attachments(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Attachment::class, InvoiceAttachment::getTableName())->using(InvoiceAttachment::class)->withPivot(['holder_name']);

    }
}
