<?php

namespace App\Models\Transaction;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Invoice extends Model
{
    use HasFactory;

    const INVOICE_STATUS_CREATED = 1;
    const INVOICE_STATUS_WAITING_PAYMENT = 2;
    const INVOICE_STATUS_WAITING_CONFIRMATION = 3;
    const INVOICE_STATUS_CONFIRMED = 4;
    const INVOICE_STATUS_PAID = 5;
    const INVOICE_STATUS_EXPIRED = 6;
    const INVOICE_STATUS_CANCELED = 7;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub


        static::creating(function (self $invoice) {
            $randomString = Str::random(5);
            $dateFormat = (Carbon::now())->format("ymd-His");
            $invoice->setAttribute($invoice->getKeyName(), $randomString."-".$dateFormat);
        });
    }
}
